#pragma once

#include "config_common.h"
#define LAYER_STATE_8BIT
#define MATRIX_UNSELECT_DRIVE_HIGH
#define MATRIX_IO_DELAY 3 //the delay in microseconds when between changing matrix pin state and reading values
#define PWM_OUTPUT_ACTIVE_LEVEL PWM_OUTPUT_ACTIVE_LOW
#define RGB_OUTPUT_ACTIVE_LEVEL RGB_OUTPUT_ACTIVE_LOW
#define SN32_PWM_CONTROL HARDWARE_PWM

// RGB_MATRIX config
#define LED_MATRIX_ROW_CHANNELS 3 //3 colors
#define LED_MATRIX_ROWS MATRIX_ROWS
#define LED_MATRIX_ROWS_HW (LED_MATRIX_ROWS * LED_MATRIX_ROW_CHANNELS)
#define LED_MATRIX_ROW_PINS { A2, A1, A0, A5, A4, A3, A8, A7, A6, A11, A10, A9, A14, A13, A12 }  //RBG order
#define LED_MATRIX_COLS MATRIX_COLS
#define LED_MATRIX_COL_PINS MATRIX_COL_PINS
#define MATRIX_LED_TOTAL 66

#define UNDERGLOW_I2C_ADR 0xE8  //AD is connected to ground (1110100(0)=0xE8)
#define UNDERGLOW_LED_TOTAL 43
#define RGB_MATRIX_LED_COUNT (MATRIX_LED_TOTAL + UNDERGLOW_LED_TOTAL)
#define RGB_MATRIX_LED_PROCESS_LIMIT 1 //needed because i2c for underglow is slow. Too many LEDs at once will result in low scan rate. Also fixes stutter.
#define RGB_DISABLE_TIMEOUT 900000 // milliseconds (15min)
#define RGB_DISABLE_WHEN_USB_SUSPENDED 1



// RGB Matrix Effects
#define ENABLE_RGB_MATRIX_ALPHAS_MODS
#define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#define ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_BREATHING
#define ENABLE_RGB_MATRIX_BAND_SAT
#define ENABLE_RGB_MATRIX_BAND_VAL
#define ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#define ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#define ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#define ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#define ENABLE_RGB_MATRIX_CYCLE_ALL
#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#define ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#define ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#define ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#define ENABLE_RGB_MATRIX_DUAL_BEACON
#define ENABLE_RGB_MATRIX_RAINBOW_BEACON
#define ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
//#define ENABLE_RGB_MATRIX_RAINDROPS  //not enough RAM
//#define ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS //not enough RAM
#define ENABLE_RGB_MATRIX_HUE_BREATHING
#define ENABLE_RGB_MATRIX_HUE_PENDULUM
#define ENABLE_RGB_MATRIX_HUE_WAVE
#define ENABLE_RGB_MATRIX_PIXEL_FRACTAL
//#define ENABLE_RGB_MATRIX_PIXEL_FLOW //not enough RAM
#define ENABLE_RGB_MATRIX_PIXEL_RAIN


///framebuffer Effects not enough RAM
//#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
//#define ENABLE_RGB_MATRIX_TYPING_HEATMAP
//#define ENABLE_RGB_MATRIX_DIGITAL_RAIN

//keypress Effects
#define RGB_MATRIX_KEYPRESSES
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#define ENABLE_RGB_MATRIX_SPLASH
#define ENABLE_RGB_MATRIX_MULTISPLASH
#define ENABLE_RGB_MATRIX_SOLID_SPLASH
#define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH

/* LED matrix Hackeroo for RAM. Uncomment to enable PWM Channel ROWS */
#define ACTIVATE_PWM_CHAN_0 //A0
#define ACTIVATE_PWM_CHAN_1 //A1
#define ACTIVATE_PWM_CHAN_2 //A2
#define ACTIVATE_PWM_CHAN_3 //A3
#define ACTIVATE_PWM_CHAN_4 //A4
#define ACTIVATE_PWM_CHAN_5 //A5
#define ACTIVATE_PWM_CHAN_6 //A6
#define ACTIVATE_PWM_CHAN_7 //A7
#define ACTIVATE_PWM_CHAN_8 //A8
#define ACTIVATE_PWM_CHAN_9 //A9
#define ACTIVATE_PWM_CHAN_10 //A10
#define ACTIVATE_PWM_CHAN_11 //A11
#define ACTIVATE_PWM_CHAN_12 //A12
#define ACTIVATE_PWM_CHAN_13 //A13
#define ACTIVATE_PWM_CHAN_14 //A14
//#define ACTIVATE_PWM_CHAN_15 //A15
//#define ACTIVATE_PWM_CHAN_16 //D0
//#define ACTIVATE_PWM_CHAN_17 //D1
//#define ACTIVATE_PWM_CHAN_18 //D2
//#define ACTIVATE_PWM_CHAN_19 //D3
//#define ACTIVATE_PWM_CHAN_21 //D5
//#define ACTIVATE_PWM_CHAN_22 //D8